import { useEffect, useState } from "react";
import { useToast } from "../../context/toastContext";
import { api } from "../../lib/api";
import { Button } from "../ui/Button";
import { Modal } from "../ui/Modal";
import styles from "./PhoneViewModal.module.css";
import { tr } from "../../i18n/i18n";

type Link = Awaited<ReturnType<typeof api.viewerLink>>;

/** QR code that opens the live call (captions, translation, scam alerts) on a phone. */
export function PhoneViewModal({ onClose }: { onClose: () => void }) {
  const notify = useToast();
  const [link, setLink] = useState<Link | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    api.viewerLink().then(
      (result) => !cancelled && setLink(result),
      (err: Error) => !cancelled && setError(err.message),
    );
    return () => {
      cancelled = true;
    };
  }, []);

  const copy = async () => {
    if (!link) return;
    await navigator.clipboard.writeText(link.url);
    notify(tr("Link kopyalandı", "Link copied"), "success");
  };

  return (
    <Modal
      eyebrow={tr("Telefonda göstər", "Show on phone")}
      title={tr("Zəngi telefonda canlı izlə", "Watch the call live on your phone")}
      onClose={onClose}
    >
      {error && <p className={styles.error}>{error}</p>}
      {!link && !error && (
        <p className={styles.hint}>{tr("QR kod hazırlanır…", "Preparing the QR code…")}</p>
      )}
      {link && (
        <div className={styles.layout}>
          {/* SVG generated by our own server from the link below. */}
          <div className={styles.qr} dangerouslySetInnerHTML={{ __html: link.qr }} />
          {link.demo ? (
            <p className={styles.steps}>
              {tr(
                "Telefonun kamerası ilə skan edin: DuyAI demosu telefonda açılacaq. Zəngin telefonda canlı göstərilməsi tam (lokal) versiyada eyni Wi-Fi şəbəkəsində işləyir.",
                "Scan with your phone camera to open the DuyAI demo on the phone. Live mirroring of a call to the phone works in the full (local) version on the same Wi-Fi.",
              )}
            </p>
          ) : (
            <ol className={styles.steps}>
              <li>
                {tr(
                  "Telefon və kompüter eyni Wi-Fi şəbəkəsində olsun.",
                  "Phone and computer must be on the same Wi-Fi.",
                )}
              </li>
              <li>
                {tr(
                  "Telefonun kamerası ilə QR kodu skan edin.",
                  "Scan the QR code with the phone camera.",
                )}
              </li>
              <li>
                {tr(
                  "Danışıq, tərcümə və dələduzluq xəbərdarlıqları telefonda canlı görünəcək. Səhifə yalnız baxmaq üçündür.",
                  "The conversation, translations and scam alerts appear live on the phone. The page is read-only.",
                )}
              </li>
            </ol>
          )}
          <div className={styles.url}>
            <code>{link.url}</code>
            <Button size="sm" icon="copy" onClick={() => void copy()}>
              {tr("Kopyala", "Copy")}
            </Button>
          </div>
          {link.alternatives.length > 0 && (
            <details className={styles.more}>
              <summary>
                {tr("Açılmırsa, digər ünvanları sınayın", "Not opening? Try the other addresses")}
              </summary>
              <ul>
                {link.alternatives.map((alt) => (
                  <li key={alt.url}>
                    <code>{alt.url}</code> <span>({alt.adapter})</span>
                  </li>
                ))}
              </ul>
            </details>
          )}
          <p className={styles.hint}>
            {tr(
              'Açılmırsa, Windows Firewall Node.js-ə "Özəl şəbəkə" icazəsi verməlidir. Link yalnız sizin şəbəkənizdə işləyir və server hər dəfə başlayanda dəyişir.',
              'If it does not open, Windows Firewall must allow Node.js on "Private networks". The link works only on your network and changes every time the server starts.',
            )}
          </p>
        </div>
      )}
    </Modal>
  );
}
